### ISSUE TITLE
I dont see my dstat on your website :D 

### ISSUE THREAD

**Issue by GermanKingYT** [hellshltd/dstatnode#2]
show up

**Comment by timmyrs** [comment]
Can you send the full log?

**Comment by GermanKingYT** [comment]
./start.sh
     _        _            _         _   _
  __| |  ___ | |_   __ _  | |_      | | (_) __ __  ___
 / _` | (_-< |  _| / _` | |  _|  _  | | | | \ V / / -_)
 \__,_| /__/  \__| \__,_|  \__| (_) |_| |_|  \_/  \___|

IPv4: 109.230.238.55
IPv6: java.net.SocketException: Network is unreachable (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:580)
        at java.net.Socket.connect(Socket.java:529)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1062)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:916)
        at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2489)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
        at live.dstat.dstatnode.Main.request(Main.java:163)
        at live.dstat.dstatnode.Main.main(Main.java:99)
Unable to determine
Thank you. Your node is live at https://dstat.live/
^Croot@debian:/var/www/html/dstat# ./start.sh
     _        _            _         _   _
  __| |  ___ | |_   __ _  | |_      | | (_) __ __  ___
 / _` | (_-< |  _| / _` | |  _|  _  | | | | \ V / / -_)
 \__,_| /__/  \__| \__,_|  \__| (_) |_| |_|  \_/  \___|

IPv4: 109.230.238.55
IPv6: java.net.SocketException: Network is unreachable (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:580)
        at java.net.Socket.connect(Socket.java:529)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1062)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:916)
        at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2489)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
        at live.dstat.dstatnode.Main.request(Main.java:163)
        at live.dstat.dstatnode.Main.main(Main.java:99)
Unable to determine
Thank you. Your node is live at https://dstat.live/

**Comment by timmyrs** [comment]
Can you try again now?

**Comment by GermanKingYT** [comment]
dont work :D

**Comment by timmyrs** [comment]
I've published the new version 1.1, please download it and try again: http://dstat.live/dstatnode.zip

**Comment by GermanKingYT** [comment]
ahhhhhhhhhhhhhhhhhhhh :D kommst du heute nochmal irc oder ts ?

**Comment by timmyrs** [comment]
Ich bin permanent auf chat.freenode.net, du kannst mich glaube einfach per Privatchat anschreiben, aber ich kann auch grad mal auf den TS kommen.
